#ifndef LCD_CONFIG_H_
#define LCD_CONFIG_H_


#define LCD_CTRL_PORT			DIO_PORTA/* LCD_RS ; LCD_RW ; LCD_EN*/
#define LCD_DATA_PORT			DIO_PORTC

#define LCD_RS_CTRL_PIN			DIO_PIN0
#define LCD_RW_CTRL_PIN			DIO_PIN1
#define LCD_EN_CTRL_PIN			DIO_PIN2

#endif/* LCD_CONFIG_H_ */
